
title: Cayla Denning
email: cayla.denning@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "//cayladenning.me"

linkedin_username: cayla-denning-170237114

# Build settings
markdown: kramdown
#theme: minima
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
plugins_dir:
  - jekyll-feed