# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cayla Denning
email: cnd6098@g.rit.edu
description: >- # this means to ignore newlines until "baseurl:"
  Engineer
baseurl: "" # the subpath of your site, e.g. /blog
#url: "//benhoffman.tech"

# Build settings
markdown: kramdown
theme: minima
plugins_dir:
  - jekyll-feed